config/routes.rb
Traveljournal::Application.routes.draw do
  resources :trips

  resources :cities do
    resources :hotels
  end

  root :to => "hotels#index"

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :hotels
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :description

  validates :rate,
            :presence => true,
            :numericality => true

  validates_associated :city
  validates_presence_of :city

  belongs_to :city
  has_many :trips

  def self.cheap
    where("rate < 100")
  end

  def self.rated(stars = 3)
    where("star_rating >= ?", stars)
  end

  def self.dallas
    where("city_id = 1")
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_filter :load_hotel, :except => [:index, :new, :create]
  def index
    city = City.find(params[:city_id])
    @hotels = city.hotels
  end

  def new
    @hotel = Hotel.new
  end

  def show
  end

  def create
    @hotel = Hotel.new(params[:hotel])
    if @hotel.save
      flash[:success] = "Congrats! You created a hotel!"
      redirect_to city_hotel_path(@hotel.city, @hotel)
    else
      flash[:error] = "There was a problem saving your hotel."
      render "new"
    end
  end

  protected
  def load_hotel
    @hotel = Hotel.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_current_date
    formatted_date(Time.zone.now)
  end
  def formatted_date(date)
    date.strftime("%m/%d/%Y")
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
  def display_title(hotel)
    content = "#{hotel.name} ("
    1.upto hotel.star_rating.to_i do
      content += "*"
    end
    content += ")"
    content
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/hotels/index.html.erb
<h1>Hotel list</h1>
<ul>
  <% @hotels.each do |hotel| %>
  <li class='hotel'><%= link_to hotel.name, city_hotel_path( hotel.city, hotel) %></li>
  <% end %>
</ul>

app/views/hotels/new.html.erb
<%= simple_form_for(@hotel, :url => city_hotels_path(@hotel.city)) do |f| %>
    <%= f.input :name %>
    <%= f.input :rate %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :city_id, :collection => City.all %>
    <%= f.button :submit, "Save Hotel" %>
<% end %>

app/views/hotels/show.html.haml
%h1= display_title(@hotel)
.hotel
  .address= @hotel.address
  .description= @hotel.description
  .rate= "#{@hotel.rate} a night"
  .actions
    .edit= link_to "Edit", edit_city_hotel_path(@hotel.city, @hotel)
    .delete= link_to "Delete", city_hotel_path(@hotel.city, @hotel), :method => :delete

app/views/layouts/application.html.erb
<html>
<head>
  <title>Traveljournal</title>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- This is where the view starts -->
<div id='flash'>
  <% [:success, :error, :notice].each do |type| %>
      <% if flash[type].present? %>
          <div class='<%= type.to_s %>'><%= flash[type] %></div>
      <% end %>
  <% end %>
</div>
<%= yield %>
<!-- This is where the view ends -->

</body>
</html>

app/views/trips/index.html.erb
<h1>Trips as of <%= formatted_current_date %></h1>
<ul>
  <% @trips.each do |trip| %>
    <li><%= trip.name %> - <%= formatted_date(trip.date) %></li>
  <% end %>
</ul>

app/views/trips/show.html.haml
%h1 Trips#show
%p Find me in app/views/trips/show.html.haml